# Max X/Z position player can reach before GeyserFloatingPoints re-position them to a position that is closer to 0 0 0.
capped-value: 3000

# Distance from fake Y center (128) before switching the remapped vertical window.
# Default 96 means switching at fake Y 32 and 224. Maximum is 192.
vertical-remap-threshold: 96

# Show real player position by default without running the command.
show-position-by-default: true